services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    container_name: chat-backend
    expose:
      - '4000'
    environment:
      - NODE_ENV=production
      - CORS_ORIGIN=http://localhost:3000,http://frontend:3000
    networks:
      - chat-network
    restart: unless-stopped
    depends_on: 
      - frontend

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    container_name: chat-frontend
    expose:
      - '3000'
    networks:
      - chat-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

